package info.bschambers.gridgeom.testgui;

import info.bschambers.gridgeom.*;

public class App {

    private static void createAndShowGUI() {

        CanvasMode[] modes = new CanvasMode[] {
            new ShapeEditMode(),
            new ShapesBooleanMode(),
            new ShapeAndLineMode(),
            new LineIntersectionMode(),
            new LineAngleMode(),
        };

        TestFrame frame
            = new TestFrame("grid-triangulation interactive tester",
                            modes, makeShapeSets());
        frame.showFrame(0, 0, 1200, 800);
    }

    public static void main(String[] args) {
        System.out.println("running interactive testing app...");
        // Schedule a job for the event-dispatching thread:
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() { createAndShowGUI(); }
            });
    }



    /*--------------------------- SHAPE SETS ---------------------------*/

    private static ShapeSet[] makeShapeSets() {
        return new ShapeSet[] {
            makeSimpleShapes(),
            makeMultipleShapes(),
            makePerforatedShapes(),
            makeTrickyTriangulationShapes(),
            makeSharedVerticesShapes(),
            makeTrickyOtherShapes(),
            makeFaultyShapes(),
        };
    }

    private static ShapeSet makeSimpleShapes() {
        return new ShapeSet("simple",

                            // CONVEX
        
                            new ShapeWrapper("triangle",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(0, 3)))),

                            new ShapeWrapper("rectangle 3x5",
                                             new Shape45(new Pt2D(0, 0),
                                                         new Pt2D(3, 0),
                                                         new Pt2D(3, 5),
                                                         new Pt2D(0, 5))),

                            new ShapeWrapper("convex polygon 1",
                                             new Shape45(new Pt2D(0, 1),
                                                         new Pt2D(1, 0),
                                                         new Pt2D(2, 0),
                                                         new Pt2D(6, 4),
                                                         new Pt2D(6, 6),
                                                         new Pt2D(2, 6),
                                                         new Pt2D(0, 4))),
        
                            // NON-CONVEX
                            
                            new ShapeWrapper("non-convex rectilinear 1",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(5, 0),
                                                                        new Pt2D(5, 2),
                                                                        new Pt2D(3, 2),
                                                                        new Pt2D(3, 3),
                                                                        new Pt2D(7, 3),
                                                                        new Pt2D(7, 1),
                                                                        new Pt2D(8, 1),
                                                                        new Pt2D(8, 5),
                                                                        new Pt2D(0, 5)))),
                       
                            new ShapeWrapper("non-convex rectilinear 2",
                                             new Shape45(new Pt2D(0, 0),
                                                         new Pt2D(3, 0),
                                                         new Pt2D(3, 4),
                                                         new Pt2D(5, 4),
                                                         new Pt2D(5, 0),
                                                         new Pt2D(6, 0),
                                                         new Pt2D(6, 6),
                                                         new Pt2D(2, 6),
                                                         new Pt2D(2, 1),
                                                         new Pt2D(0, 1))),

                            new ShapeWrapper("cross 1",
                                             new Shape45(new Pt2D(2, 0),
                                                         new Pt2D(4, 0),
                                                         new Pt2D(4, 2),
                                                         new Pt2D(6, 2),
                                                         new Pt2D(6, 4),
                                                         new Pt2D(4, 4),
                                                         new Pt2D(4, 6),
                                                         new Pt2D(2, 6),
                                                         new Pt2D(2, 4),
                                                         new Pt2D(0, 4),
                                                         new Pt2D(0, 2),
                                                         new Pt2D(2, 2))),
        
                            new ShapeWrapper("cross 2",
                                             new Shape45(new Pt2D(2, 0),
                                                         new Pt2D(3, 0),
                                                         new Pt2D(3, 3),
                                                         new Pt2D(6, 3),
                                                         new Pt2D(6, 4),
                                                         new Pt2D(3, 4),
                                                         new Pt2D(3, 6),
                                                         new Pt2D(2, 6),
                                                         new Pt2D(2, 4),
                                                         new Pt2D(0, 4),
                                                         new Pt2D(0, 3),
                                                         new Pt2D(2, 3))),

                            new ShapeWrapper("maze 1",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 4),
                                                                        new Pt2D(1, 4),
                                                                        new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(2, 4),
                                                                        new Pt2D(10, 4),
                                                                        new Pt2D(10, 5),
                                                                        new Pt2D(5, 5),
                                                                        new Pt2D(5, 9),
                                                                        new Pt2D(6, 9),
                                                                        new Pt2D(6, 7),
                                                                        new Pt2D(7, 7),
                                                                        new Pt2D(7, 10),
                                                                        new Pt2D(4, 10),
                                                                        new Pt2D(4, 5),
                                                                        new Pt2D(0, 5)))),

                            new ShapeWrapper("maze 2",
                                             new ShapeGroup(new Shape45(new Pt2D(1, 2),
                                                                        new Pt2D(2, 2),
                                                                        new Pt2D(7, 7),
                                                                        new Pt2D(9, 5),
                                                                        new Pt2D(9, 3),
                                                                        new Pt2D(6, 0),
                                                                        new Pt2D(7, 0),
                                                                        new Pt2D(10, 3),
                                                                        new Pt2D(10, 6),
                                                                        new Pt2D(8, 8),
                                                                        new Pt2D(9, 9),
                                                                        new Pt2D(9, 10),
                                                                        new Pt2D(5, 6),
                                                                        new Pt2D(4, 6),
                                                                        new Pt2D(0, 10),
                                                                        new Pt2D(0, 9),
                                                                        new Pt2D(4, 5)))),

                            new ShapeWrapper("zig-zag outline",
                                             new ShapeGroup(new Shape45(new Pt2D(2, 7),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 4),
                                                                        new Pt2D(1, 3),
                                                                        new Pt2D(0, 2),
                                                                        new Pt2D(1, 1),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(5, 3),
                                                                        new Pt2D(6, 2),
                                                                        new Pt2D(7, 3),
                                                                        new Pt2D(8, 2),
                                                                        new Pt2D(9, 3),
                                                                        new Pt2D(10, 2),
                                                                        new Pt2D(11, 3),
                                                                        new Pt2D(10, 4),
                                                                        new Pt2D(12, 6),
                                                                        new Pt2D(12, 7),
                                                                        new Pt2D(10, 5),
                                                                        new Pt2D(9, 6),
                                                                        new Pt2D(10, 7),
                                                                        new Pt2D(9, 8),
                                                                        new Pt2D(10, 9),
                                                                        new Pt2D(9, 10),
                                                                        new Pt2D(10, 11),
                                                                        new Pt2D(9, 12),
                                                                        new Pt2D(10, 13),
                                                                        new Pt2D(9, 14),
                                                                        new Pt2D(8, 13),
                                                                        new Pt2D(7, 14),
                                                                        new Pt2D(6, 13),
                                                                        new Pt2D(5, 14),
                                                                        new Pt2D(4, 13),
                                                                        new Pt2D(3, 14),
                                                                        new Pt2D(2, 13),
                                                                        new Pt2D(3, 12),
                                                                        new Pt2D(2, 11),
                                                                        new Pt2D(3, 10),
                                                                        new Pt2D(2, 9),
                                                                        new Pt2D(3, 8))))

                            );
    }

    private static ShapeSet makeMultipleShapes() {
        return new ShapeSet("multiple",
                            
                            new ShapeWrapper("multiple 1",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(3, 2),
                                                                        new Pt2D(0, 2)),
                                                            new Shape45(new Pt2D(0, 3),
                                                                        new Pt2D(3, 3),
                                                                        new Pt2D(3, 5),
                                                                        new Pt2D(0, 5)))),

                            new ShapeWrapper("shared vertices 1 (chequer board)",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(2, 2),
                                                                        new Pt2D(0, 2)),
                                                            new Shape45(new Pt2D(4, 0),
                                                                        new Pt2D(6, 0),
                                                                        new Pt2D(6, 2),
                                                                        new Pt2D(4, 2)),
                                                            new Shape45(new Pt2D(2, 2),
                                                                        new Pt2D(4, 2),
                                                                        new Pt2D(4, 4),
                                                                        new Pt2D(2, 4)),
                                                            new Shape45(new Pt2D(6, 2),
                                                                        new Pt2D(8, 2),
                                                                        new Pt2D(8, 4),
                                                                        new Pt2D(6, 4)),
                                                            new Shape45(new Pt2D(0, 4),
                                                                        new Pt2D(2, 4),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 6)),
                                                            new Shape45(new Pt2D(4, 4),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(4, 6)),
                                                            new Shape45(new Pt2D(2, 6),
                                                                        new Pt2D(4, 6),
                                                                        new Pt2D(4, 8),
                                                                        new Pt2D(2, 8)),
                                                            new Shape45(new Pt2D(6, 6),
                                                                        new Pt2D(8, 6),
                                                                        new Pt2D(8, 8),
                                                                        new Pt2D(6, 8)))),

                            new ShapeWrapper("shared vertices 2",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 2),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(3, 3),
                                                                        new Pt2D(2, 2)),
                                                            new Shape45(new Pt2D(6, 0),
                                                                        new Pt2D(6, 2),
                                                                        new Pt2D(3, 5),
                                                                        new Pt2D(0, 5),
                                                                        new Pt2D(0, 3),
                                                                        new Pt2D(3, 3)),
                                                            new Shape45(new Pt2D(4, 5),
                                                                        new Pt2D(6, 3),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(4, 6),
                                                                        new Pt2D(3, 6),
                                                                        new Pt2D(1, 8),
                                                                        new Pt2D(0, 8),
                                                                        new Pt2D(0, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(3, 5)),
                                                            new Shape45(new Pt2D(5, 6),
                                                                        new Pt2D(6, 5),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(5, 7),
                                                                        new Pt2D(4, 7),
                                                                        new Pt2D(3, 8),
                                                                        new Pt2D(2, 8),
                                                                        new Pt2D(4, 6)),
                                                            new Shape45(new Pt2D(6, 7),
                                                                        new Pt2D(6, 8),
                                                                        new Pt2D(5, 8),
                                                                        new Pt2D(5, 7)),
                                                            new Shape45(new Pt2D(5, 0),
                                                                        new Pt2D(4, 1),
                                                                        new Pt2D(3, 0))))

                            );
    }

    private static ShapeSet makePerforatedShapes() {
        return new ShapeSet("perforated",

                            new ShapeWrapper("nested boxes 1",
                                             new Shape45(new Shape45(new Pt2D(1, 4),
                                                                     new Pt2D(1, 5),
                                                                     new Pt2D(3, 5),
                                                                     new Pt2D(3, 4)),
                                                         new Pt2D(0, 0),
                                                         new Pt2D(6, 0),
                                                         new Pt2D(6, 6),
                                                         new Pt2D(0, 6))),
        
                            new ShapeWrapper("nested boxes 2",
                                             new Shape45(new Shape45[] {
                                                     new Shape45(new Pt2D(1, 4),
                                                                 new Pt2D(1, 5),
                                                                 new Pt2D(3, 5),
                                                                 new Pt2D(3, 4)),
                                                     new Shape45(new Pt2D(4, 1),
                                                                 new Pt2D(4, 5),
                                                                 new Pt2D(5, 5),
                                                                 new Pt2D(5, 1)),
                                                 },
                                                 new Pt2D(0, 0),
                                                 new Pt2D(6, 0),
                                                 new Pt2D(6, 6),
                                                 new Pt2D(0, 6))),

                            new ShapeWrapper("nested boxes 3",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(1, 4),
                                                                     new Pt2D(1, 5),
                                                                     new Pt2D(3, 5),
                                                                     new Pt2D(3, 4)),
                                                         new Shape45(new Pt2D(4, 1),
                                                                     new Pt2D(4, 5),
                                                                     new Pt2D(5, 5),
                                                                     new Pt2D(5, 1)),
                                                         new Shape45(new Pt2D(1, 1),
                                                                     new Pt2D(1, 3),
                                                                     new Pt2D(3, 3),
                                                                     new Pt2D(3, 1)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(6, 0),
                                                     new Pt2D(6, 6),
                                                     new Pt2D(0, 6)))),

                            new ShapeWrapper("nested boxes 4",
                                             new ShapeGroup(new Shape45(new Shape45(new Shape45(new Shape45(new Pt2D(3, 8),
                                                                                                            new Pt2D(6, 8),
                                                                                                            new Pt2D(6, 3),
                                                                                                            new Pt2D(3, 3)),
                                                                                                new Pt2D(2, 2),
                                                                                                new Pt2D(7, 2),
                                                                                                new Pt2D(7, 9),
                                                                                                new Pt2D(2, 9)),
                                                                                    new Pt2D(1, 10),
                                                                                    new Pt2D(8, 10),
                                                                                    new Pt2D(8, 1),
                                                                                    new Pt2D(1, 1)),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(9, 0),
                                                                        new Pt2D(9, 11),
                                                                        new Pt2D(0, 11)))),

                            new ShapeWrapper("nested boxes 5",
                                             new ShapeGroup(new Shape45(new Shape45(new Shape45(new Shape45(new Pt2D(3, 4),
                                                                                                            new Pt2D(3, 6),
                                                                                                            new Pt2D(4, 6),
                                                                                                            new Pt2D(4, 4)),
                                                                                                new Pt2D(2, 3),
                                                                                                new Pt2D(5, 3),
                                                                                                new Pt2D(5, 9),
                                                                                                new Pt2D(2, 9)),
                                                                                    new Pt2D(1, 2),
                                                                                    new Pt2D(1, 13),
                                                                                    new Pt2D(7, 13),
                                                                                    new Pt2D(7, 2)),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(20, 0),
                                                                        new Pt2D(20, 14),
                                                                        new Pt2D(0, 14)))),
                            
                            new ShapeWrapper("nested boxes 6",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Shape45[] {
                                                                 new Shape45(new Shape45[] {
                                                                         new Shape45(new Pt2D(3, 4),
                                                                                     new Pt2D(3, 6),
                                                                                     new Pt2D(4, 6),
                                                                                     new Pt2D(4, 4)),
                                                                         new Shape45(new Pt2D(3, 7),
                                                                                     new Pt2D(3, 8),
                                                                                     new Pt2D(4, 7)),
                                                                     },
                                                                     new Pt2D(2, 3),
                                                                     new Pt2D(5, 3),
                                                                     new Pt2D(5, 9),
                                                                     new Pt2D(2, 9)),
                                                                 new Shape45(new Pt2D(6, 10),
                                                                             new Pt2D(6, 12),
                                                                             new Pt2D(2, 12),
                                                                             new Pt2D(2, 10)),
                                                             },
                                                             new Pt2D(1, 2),
                                                             new Pt2D(1, 13),
                                                             new Pt2D(7, 13),
                                                             new Pt2D(7, 2)),
                                                         new Shape45(new Shape45[] {
                                                                 new Shape45(new Pt2D(12, 2),
                                                                             new Pt2D(12, 9),
                                                                             new Pt2D(18, 9),
                                                                             new Pt2D(18, 11),
                                                                             new Pt2D(10, 11),
                                                                             new Pt2D(10, 2)),
                                                                 new Shape45(new Pt2D(14, 2),
                                                                             new Pt2D(14, 8),
                                                                             new Pt2D(13, 8),
                                                                             new Pt2D(13, 2)),
                                                                 new Shape45(new Shape45[] {
                                                                         new Shape45(new Pt2D(16, 5),
                                                                                     new Pt2D(16, 7),
                                                                                     new Pt2D(17, 7),
                                                                                     new Pt2D(17, 5)),
                                                                         new Shape45(new Pt2D(16, 3),
                                                                                     new Pt2D(16, 4),
                                                                                     new Pt2D(17, 4),
                                                                                     new Pt2D(17, 3)),
                                                                     },
                                                                     new Pt2D(18, 2),
                                                                     new Pt2D(18, 8),
                                                                     new Pt2D(15, 8),
                                                                     new Pt2D(15, 2)),
                                                             },
                                                             new Pt2D(9, 1),
                                                             new Pt2D(9, 12),
                                                             new Pt2D(19, 12),
                                                             new Pt2D(19, 1)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(20, 0),
                                                     new Pt2D(20, 14),
                                                     new Pt2D(0, 14)))),
                            
                            new ShapeWrapper("perforated (3 levels)",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Shape45(new Pt2D(5, 2),
                                                                                 new Pt2D(10, 2),
                                                                                 new Pt2D(9, 3),
                                                                                 new Pt2D(9, 6)),
                                                                     new Pt2D(9, 7),
                                                                     new Pt2D(11, 7),
                                                                     new Pt2D(11, 1),
                                                                     new Pt2D(3, 1)),
                                                         new Shape45(new Pt2D(12, 1),
                                                                     new Pt2D(12, 7),
                                                                     new Pt2D(14, 7),
                                                                     new Pt2D(14, 1)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(17, 0),
                                                     new Pt2D(15, 2),
                                                     new Pt2D(15, 8),
                                                     new Pt2D(2, 8),
                                                     new Pt2D(2, 2)))),
                            
                            new ShapeWrapper("nested triangles (3 levels)",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Shape45[] {
                                                                 new Shape45(new Pt2D(16, 6),
                                                                             new Pt2D(16, 9),
                                                                             new Pt2D(13, 9)),
                                                                 new Shape45(new Pt2D(15, 5),
                                                                             new Pt2D(13, 7),
                                                                             new Pt2D(13, 5)),
                                                             },
                                                             new Pt2D(12, 10),
                                                             new Pt2D(21, 10),
                                                             new Pt2D(12, 1)),
                                                         new Shape45(new Pt2D(26, 3),
                                                                     new Pt2D(28, 3),
                                                                     new Pt2D(26, 1)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(32, 0),
                                                     new Pt2D(16, 16)))),

                            new ShapeWrapper("perforated (4 levels)",
                                             new ShapeGroup(new Shape45(new Shape45(new Shape45[] {
                                                             new Shape45(new Shape45[] {
                                                                     new Shape45(new Pt2D(6, 8),
                                                                                 new Pt2D(7, 8),
                                                                                 new Pt2D(7, 5),
                                                                                 new Pt2D(6, 5)),
                                                                     new Shape45(new Pt2D(9, 5),
                                                                                 new Pt2D(9, 8),
                                                                                 new Pt2D(10, 8),
                                                                                 new Pt2D(10, 5),
                                                                                 new Pt2D(11, 5),
                                                                                 new Pt2D(11, 4),
                                                                                 new Pt2D(8, 4)),
                                                                 },
                                                                 new Pt2D(3, 6),
                                                                 new Pt2D(6, 3),
                                                                 new Pt2D(14, 3),
                                                                 new Pt2D(11, 6),
                                                                 new Pt2D(11, 10),
                                                                 new Pt2D(6, 10),
                                                                 new Pt2D(5, 9),
                                                                 new Pt2D(5, 8)),
                                                             new Shape45(new Pt2D(13, 7),
                                                                         new Pt2D(13, 11),
                                                                         new Pt2D(12, 10),
                                                                         new Pt2D(12, 6)),
                                                         },
                                                         new Pt2D(1, 6),
                                                         new Pt2D(6, 11),
                                                         new Pt2D(12, 11),
                                                         new Pt2D(14, 13),
                                                         new Pt2D(14, 5),
                                                         new Pt2D(15, 5),
                                                         new Pt2D(15, 2),
                                                         new Pt2D(7, 2),
                                                         new Pt2D(6, 1)),
                                                     new Pt2D(0, 7),
                                                     new Pt2D(0, 4),
                                                     new Pt2D(3, 1),
                                                     new Pt2D(4, 2),
                                                     new Pt2D(6, 0),
                                                     new Pt2D(17, 0),
                                                     new Pt2D(17, 2),
                                                     new Pt2D(16, 3),
                                                     new Pt2D(17, 4),
                                                     new Pt2D(17, 6),
                                                     new Pt2D(15, 8),
                                                     new Pt2D(15, 14),
                                                     new Pt2D(11, 14),
                                                     new Pt2D(9, 12),
                                                     new Pt2D(7, 14),
                                                     new Pt2D(5, 14),
                                                     new Pt2D(2, 11),
                                                     new Pt2D(3, 10)))),

                            new ShapeWrapper("perforated (7 levels)",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Shape45(new Shape45[] {
                                                                     new Shape45(new Shape45[] {
                                                                             new Shape45(new Shape45[] {
                                                                                     new Shape45(new Shape45[] {
                                                                                             new Shape45(new Pt2D(6, 8),
                                                                                                         new Pt2D(9, 8),
                                                                                                         new Pt2D(9, 9),
                                                                                                         new Pt2D(6, 9)),
                                                                                             new Shape45(new Pt2D(13, 8),
                                                                                                         new Pt2D(13, 11),
                                                                                                         new Pt2D(12, 11),
                                                                                                         new Pt2D(12, 9),
                                                                                                         new Pt2D(11, 9),
                                                                                                         new Pt2D(11, 8)),
                                                                                         },
                                                                                         new Pt2D(5, 10),
                                                                                         new Pt2D(11, 10),
                                                                                         new Pt2D(11, 12),
                                                                                         new Pt2D(14, 12),
                                                                                         new Pt2D(14, 7),
                                                                                         new Pt2D(5, 7)),
                                                                                     new Shape45(new Pt2D(15, 10),
                                                                                                 new Pt2D(15, 12),
                                                                                                 new Pt2D(16, 12),
                                                                                                 new Pt2D(16, 10)),
                                                                                 },
                                                                                 new Pt2D(4, 6),
                                                                                 new Pt2D(14, 6),
                                                                                 new Pt2D(17, 9),
                                                                                 new Pt2D(17, 13),
                                                                                 new Pt2D(10, 13),
                                                                                 new Pt2D(10, 11),
                                                                                 new Pt2D(4, 11)),
                                                                             new Shape45(new Pt2D(5, 12),
                                                                                         new Pt2D(5, 13),
                                                                                         new Pt2D(4, 13),
                                                                                         new Pt2D(4, 12)),
                                                                         },
                                                                         new Pt2D(3, 14),
                                                                         new Pt2D(6, 14),
                                                                         new Pt2D(8, 12),
                                                                         new Pt2D(10, 14),
                                                                         new Pt2D(18, 14),
                                                                         new Pt2D(18, 9),
                                                                         new Pt2D(14, 5),
                                                                         new Pt2D(4, 5),
                                                                         new Pt2D(3, 6)),
                                                                     new Shape45(new Pt2D(8, 14),
                                                                                 new Pt2D(7, 15),
                                                                                 new Pt2D(8, 16),
                                                                                 new Pt2D(9, 15)),
                                                                 },
                                                                 new Pt2D(2, 6),
                                                                 new Pt2D(4, 4),
                                                                 new Pt2D(14, 4),
                                                                 new Pt2D(19, 9),
                                                                 new Pt2D(19, 14),
                                                                 new Pt2D(17, 16),
                                                                 new Pt2D(17, 15),
                                                                 new Pt2D(10, 15),
                                                                 new Pt2D(8, 17),
                                                                 new Pt2D(6, 15),
                                                                 new Pt2D(2, 15)),
                                                             new Pt2D(1, 15),
                                                             new Pt2D(4, 18),
                                                             new Pt2D(9, 18),
                                                             new Pt2D(11, 16),
                                                             new Pt2D(16, 16),
                                                             new Pt2D(17, 17),
                                                             new Pt2D(20, 14),
                                                             new Pt2D(20, 9),
                                                             new Pt2D(14, 3),
                                                             new Pt2D(4, 3),
                                                             new Pt2D(1, 6)),
                                                         new Shape45(new Pt2D(7, 1),
                                                                     new Pt2D(7, 2),
                                                                     new Pt2D(10, 2),
                                                                     new Pt2D(9, 1)),
                                                     },
                                                     new Pt2D(0, 6),
                                                     new Pt2D(6, 0),
                                                     new Pt2D(10, 0),
                                                     new Pt2D(12, 2),
                                                     new Pt2D(14, 2),
                                                     new Pt2D(21, 9),
                                                     new Pt2D(21, 14),
                                                     new Pt2D(16, 19),
                                                     new Pt2D(4, 19),
                                                     new Pt2D(0, 15))))

                            );

    }

    /**
     * <p>Valid shapes which pose problems for triangulation.</p>
     */
    private static ShapeSet makeTrickyTriangulationShapes() {
        return new ShapeSet("tricky triangulation",

                            // COLLINEAR VERTICES
                            
                            new ShapeWrapper("collinear vertices 1 (convex)",
                                             new ShapeGroup(new Shape45(new Pt2D(3, 0),
                                                                        new Pt2D(3, 2),
                                                                        new Pt2D(3, 5),
                                                                        new Pt2D(0, 5),
                                                                        new Pt2D(0, 0)))),
                            
                            new ShapeWrapper("collinear vertices 2 (convex big square)",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 4),
                                                                        new Pt2D(0, 3),
                                                                        new Pt2D(0, 1),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(6, 0),
                                                                        new Pt2D(9, 0),
                                                                        new Pt2D(10, 0),
                                                                        new Pt2D(12, 0),
                                                                        new Pt2D(12, 4),
                                                                        new Pt2D(12, 8),
                                                                        new Pt2D(12, 12),
                                                                        new Pt2D(11, 12),
                                                                        new Pt2D(10, 12),
                                                                        new Pt2D(9, 12),
                                                                        new Pt2D(7, 12),
                                                                        new Pt2D(5, 12),
                                                                        new Pt2D(0, 12),
                                                                        new Pt2D(0, 6),
                                                                        new Pt2D(0, 5)))),
                            
                            new ShapeWrapper("collinear vertices 3 (convex octagon)",
                                             new ShapeGroup(new Shape45(new Pt2D(14, 4),
                                                                        new Pt2D(11, 7),
                                                                        new Pt2D(9, 9),
                                                                        new Pt2D(8, 10),
                                                                        new Pt2D(7, 11),
                                                                        new Pt2D(5, 13),
                                                                        new Pt2D(4, 13),
                                                                        new Pt2D(3, 12),
                                                                        new Pt2D(0, 9),
                                                                        new Pt2D(0, 6),
                                                                        new Pt2D(0, 4),
                                                                        new Pt2D(0, 3),
                                                                        new Pt2D(1, 2),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(8, 0),
                                                                        new Pt2D(10, 0),
                                                                        new Pt2D(12, 0),
                                                                        new Pt2D(14, 2)))),
                            
                            new ShapeWrapper("collinear vertices 4",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(3, 2),
                                                                        new Pt2D(3, 5),
                                                                        new Pt2D(10, 5),
                                                                        new Pt2D(10, 7),
                                                                        new Pt2D(8, 7),
                                                                        new Pt2D(4, 7),
                                                                        new Pt2D(2, 7),
                                                                        new Pt2D(1, 7),
                                                                        new Pt2D(0, 7),
                                                                        new Pt2D(0, 5)))),
                            
                            new ShapeWrapper("collinear vertices 3",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 2),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(1, 1),
                                                                        new Pt2D(1, 2),
                                                                        new Pt2D(1, 3),
                                                                        new Pt2D(1, 4),
                                                                        new Pt2D(2, 5),
                                                                        new Pt2D(2, 1),
                                                                        new Pt2D(6, 1),
                                                                        new Pt2D(6, 5),
                                                                        new Pt2D(6, 7),
                                                                        new Pt2D(2, 7),
                                                                        new Pt2D(0, 5)))),

                            // RISK OF EDGE OUTSIDE OF OUTLINE

                            new ShapeWrapper("triangulation outside edge risk 1",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 2),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(3, 3),
                                                                        new Pt2D(2, 2)))),

                            new ShapeWrapper("triangulation outside edge risk 2 (pizza hut)",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(10, 0),
                                                                        new Pt2D(8, 2),
                                                                        new Pt2D(8, 4),
                                                                        new Pt2D(2, 4),
                                                                        new Pt2D(2, 2)))),

                            // NESTED TRIANGLES

                            new ShapeWrapper("nested triangles 1",
                                             new ShapeGroup(new Shape45(new Shape45(new Pt2D(1, 4),
                                                                                    new Pt2D(4, 1),
                                                                                    new Pt2D(1, 1)),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(6, 0),
                                                                        new Pt2D(0, 6)))),

                            new ShapeWrapper("nested triangles 2",
                                             new ShapeGroup(new Shape45(new Shape45(new Shape45(new Pt2D(2, 2),
                                                                                                new Pt2D(5, 2),
                                                                                                new Pt2D(2, 5)),
                                                                                    new Pt2D(1, 7),
                                                                                    new Pt2D(7, 1),
                                                                                    new Pt2D(1, 1)),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(9, 0),
                                                                        new Pt2D(0, 9)))),

                            // INACCESSIBLE HOLES

                            new ShapeWrapper("inaccessible hole 1",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(4, 10),
                                                                     new Pt2D(5, 10),
                                                                     new Pt2D(5, 4),
                                                                     new Pt2D(4, 4)),
                                                         new Shape45(new Pt2D(6, 8),
                                                                     new Pt2D(6, 11),
                                                                     new Pt2D(3, 11),
                                                                     new Pt2D(3, 8),
                                                                     new Pt2D(2, 8),
                                                                     new Pt2D(2, 12),
                                                                     new Pt2D(7, 12),
                                                                     new Pt2D(7, 8)),
                                                         new Shape45(new Pt2D(2, 2),
                                                                     new Pt2D(2, 5),
                                                                     new Pt2D(3, 5),
                                                                     new Pt2D(3, 3),
                                                                     new Pt2D(6, 3),
                                                                     new Pt2D(6, 5),
                                                                     new Pt2D(7, 5),
                                                                     new Pt2D(7, 2)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(9, 0),
                                                     new Pt2D(9, 14),
                                                     new Pt2D(0, 14)))),
                                             
                            new ShapeWrapper("inaccessible hole 2",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(6, 8),
                                                                     new Pt2D(6, 11),
                                                                     new Pt2D(10, 11),
                                                                     new Pt2D(9, 10),
                                                                     new Pt2D(9, 8)),
                                                         new Shape45(new Pt2D(6, 5),
                                                                     new Pt2D(6, 6),
                                                                     new Pt2D(8, 6),
                                                                     new Pt2D(11, 9),
                                                                     new Pt2D(11, 13),
                                                                     new Pt2D(6, 13),
                                                                     new Pt2D(4, 11),
                                                                     new Pt2D(4, 6),
                                                                     new Pt2D(6, 4),
                                                                     new Pt2D(11, 4),
                                                                     new Pt2D(13, 6),
                                                                     new Pt2D(13, 5),
                                                                     new Pt2D(10, 2),
                                                                     new Pt2D(5, 2),
                                                                     new Pt2D(2, 5),
                                                                     new Pt2D(2, 11),
                                                                     new Pt2D(6, 15),
                                                                     new Pt2D(11, 15),
                                                                     new Pt2D(13, 13),
                                                                     new Pt2D(13, 8),
                                                                     new Pt2D(10, 5)),
                                                     },
                                                     new Pt2D(4, 0),
                                                     new Pt2D(13, 0),
                                                     new Pt2D(16, 3),
                                                     new Pt2D(16, 12),
                                                     new Pt2D(10, 18),
                                                     new Pt2D(5, 18),
                                                     new Pt2D(0, 13),
                                                     new Pt2D(0, 4))))

                            );
    }


    /**
     * <p>Valid shapes which pose problems for triangulation.</p>
     */
    private static ShapeSet makeSharedVerticesShapes() {
        return new ShapeSet("shared vertices",
    
                            // HOLE SHARES VERTEX WITH OUTLINE
                            
                            new ShapeWrapper("hole shares vertex with outline",
                                             new ShapeGroup(new Shape45(new Shape45(new Pt2D(6, 4),
                                                                                    new Pt2D(5, 3),
                                                                                    new Pt2D(2, 3),
                                                                                    new Pt2D(2, 8),
                                                                                    new Pt2D(6, 8)),
                                                                        new Pt2D(9, 0),
                                                                        new Pt2D(11, 0),
                                                                        new Pt2D(9, 2),
                                                                        new Pt2D(9, 10),
                                                                        new Pt2D(2, 10),
                                                                        new Pt2D(2, 8),
                                                                        new Pt2D(0, 8),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(5, 0),
                                                                        new Pt2D(7, 2)))),

                            new ShapeWrapper("hole shares multiple vertices with outline 1",
                                             new ShapeGroup(new Shape45(new Shape45(new Pt2D(2, 14),
                                                                                    new Pt2D(2, 16),
                                                                                    new Pt2D(8, 16),
                                                                                    new Pt2D(8, 12),
                                                                                    new Pt2D(6, 12),
                                                                                    new Pt2D(6, 14)),
                                                                        new Pt2D(9, 5),
                                                                        new Pt2D(5, 9),
                                                                        new Pt2D(8, 12),
                                                                        new Pt2D(11, 12),
                                                                        new Pt2D(11, 16),
                                                                        new Pt2D(8, 16),
                                                                        new Pt2D(6, 18),
                                                                        new Pt2D(4, 18),
                                                                        new Pt2D(2, 16),
                                                                        new Pt2D(0, 16),
                                                                        new Pt2D(0, 11),
                                                                        new Pt2D(11, 0),
                                                                        new Pt2D(11, 7)))),

                            new ShapeWrapper("hole shares multiple vertices with outline 2",
                                             new ShapeGroup(new Shape45(new Shape45(new Pt2D(6, 6),
                                                                                    new Pt2D(6, 11),
                                                                                    new Pt2D(2, 11),
                                                                                    new Pt2D(4, 13),
                                                                                    new Pt2D(4, 15),
                                                                                    new Pt2D(7, 15),
                                                                                    new Pt2D(8, 16),
                                                                                    new Pt2D(11, 13),
                                                                                    new Pt2D(9, 11),
                                                                                    new Pt2D(9, 6)),
                                                                        new Pt2D(4, 1),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(7, 0),
                                                                        new Pt2D(6, 1),
                                                                        new Pt2D(6, 3),
                                                                        new Pt2D(9, 6),
                                                                        new Pt2D(12, 6),
                                                                        new Pt2D(12, 9),
                                                                        new Pt2D(11, 10),
                                                                        new Pt2D(11, 13),
                                                                        new Pt2D(11, 15),
                                                                        new Pt2D(10, 16),
                                                                        new Pt2D(8, 16),
                                                                        new Pt2D(8, 18),
                                                                        new Pt2D(7, 18),
                                                                        new Pt2D(4, 15),
                                                                        new Pt2D(3, 16),
                                                                        new Pt2D(0, 16),
                                                                        new Pt2D(1, 15),
                                                                        new Pt2D(0, 15),
                                                                        new Pt2D(1, 14),
                                                                        new Pt2D(0, 14),
                                                                        new Pt2D(1, 13),
                                                                        new Pt2D(0, 13),
                                                                        new Pt2D(2, 11),
                                                                        new Pt2D(2, 7),
                                                                        new Pt2D(3, 6),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(4, 4)))),
                            
                            // HOLES WITH SHARED VERTICES

                            new ShapeWrapper("holes with shared vertices 1",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(1, 3),
                                                                     new Pt2D(3, 3),
                                                                     new Pt2D(3, 1),
                                                                     new Pt2D(1, 1)),
                                                         new Shape45(new Pt2D(5, 7),
                                                                     new Pt2D(7, 7),
                                                                     new Pt2D(7, 5),
                                                                     new Pt2D(5, 5)),
                                                         new Shape45(new Pt2D(3, 9),
                                                                     new Pt2D(5, 9),
                                                                     new Pt2D(5, 7),
                                                                     new Pt2D(3, 7)),
                                                         new Shape45(new Pt2D(7, 9),
                                                                     new Pt2D(9, 9),
                                                                     new Pt2D(9, 7),
                                                                     new Pt2D(7, 7)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(10, 0),
                                                     new Pt2D(10, 10),
                                                     new Pt2D(0, 10)))),
                            
                            new ShapeWrapper("holes with shared vertices 2 (chequer board)",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(1, 3),
                                                                     new Pt2D(3, 3),
                                                                     new Pt2D(3, 1),
                                                                     new Pt2D(1, 1)),
                                                         new Shape45(new Pt2D(5, 3),
                                                                     new Pt2D(7, 3),
                                                                     new Pt2D(7, 1),
                                                                     new Pt2D(5, 1)),
                                                         new Shape45(new Pt2D(3, 5),
                                                                     new Pt2D(5, 5),
                                                                     new Pt2D(5, 3),
                                                                     new Pt2D(3, 3)),
                                                         new Shape45(new Pt2D(7, 5),
                                                                     new Pt2D(9, 5),
                                                                     new Pt2D(9, 3),
                                                                     new Pt2D(7, 3)),
                                                         new Shape45(new Pt2D(1, 7),
                                                                     new Pt2D(3, 7),
                                                                     new Pt2D(3, 5),
                                                                     new Pt2D(1, 5)),
                                                         new Shape45(new Pt2D(5, 7),
                                                                     new Pt2D(7, 7),
                                                                     new Pt2D(7, 5),
                                                                     new Pt2D(5, 5)),
                                                         new Shape45(new Pt2D(3, 9),
                                                                     new Pt2D(5, 9),
                                                                     new Pt2D(5, 7),
                                                                     new Pt2D(3, 7)),
                                                         new Shape45(new Pt2D(7, 9),
                                                                     new Pt2D(9, 9),
                                                                     new Pt2D(9, 7),
                                                                     new Pt2D(7, 7)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(10, 0),
                                                     new Pt2D(10, 10),
                                                     new Pt2D(0, 10))))                            

                            );
    }
    
    private static ShapeSet makeTrickyOtherShapes() {
        return new ShapeSet("tricky (other)",

                            // WINDING PROBLEM WITH OLD (SUM-ANGLES) METHOD
                            
                            new ShapeWrapper("winding problem with old (sum-angles) method 1",
                                             new ShapeGroup(new Shape45(new Pt2D(10, 5),
                                                                        new Pt2D(10, 7),
                                                                        new Pt2D(8, 7),
                                                                        new Pt2D(8, 8),
                                                                        new Pt2D(12, 8),
                                                                        new Pt2D(12, 6),
                                                                        new Pt2D(13, 6),
                                                                        new Pt2D(13, 10),
                                                                        new Pt2D(5, 10),
                                                                        new Pt2D(0, 5),
                                                                        new Pt2D(5, 0),
                                                                        new Pt2D(7, 2),
                                                                        new Pt2D(5, 4),
                                                                        new Pt2D(5, 5)))),

                            new ShapeWrapper("winding problem with old (sum-angles) method 2",
                                             new ShapeGroup(new Shape45(new Pt2D(2, 1),
                                                                        new Pt2D(6, 1),
                                                                        new Pt2D(6, 5),
                                                                        new Pt2D(6, 7),
                                                                        new Pt2D(2, 7),
                                                                        new Pt2D(0, 5),
                                                                        new Pt2D(0, 2),
                                                                        new Pt2D(0, 0),
                                                                        new Pt2D(1, 1),
                                                                        new Pt2D(1, 2),
                                                                        new Pt2D(1, 3),
                                                                        new Pt2D(1, 4),
                                                                        new Pt2D(2, 5))))
                            
                            );
    }
    
    private static ShapeSet makeFaultyShapes() {
        return new ShapeSet("faulty shapes",

                            new ShapeWrapper("triangle (bad winding)",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(0, 3),
                                                                        new Pt2D(3, 0)))),
                            
                            new ShapeWrapper("rectangle (bad winding)",
                                             new Shape45(new Pt2D(0, 0),
                                                         new Pt2D(0, 5),
                                                         new Pt2D(3, 5),
                                                         new Pt2D(3, 0))),
        
                            new ShapeWrapper("convex polygon (bad winding)",
                                             new Shape45(new Pt2D(0, 1),
                                                         new Pt2D(0, 4),
                                                         new Pt2D(2, 6),
                                                         new Pt2D(6, 6),
                                                         new Pt2D(6, 4),
                                                         new Pt2D(2, 0),
                                                         new Pt2D(1, 0))),

                            new ShapeWrapper("multiple (mixed winding)",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(3, 2),
                                                                        new Pt2D(0, 2)),
                                                            new Shape45(new Pt2D(0, 3),
                                                                        new Pt2D(0, 5),
                                                                        new Pt2D(3, 5),
                                                                        new Pt2D(3, 3)))),

                            new ShapeWrapper("non-45 angle (convex)",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 3),
                                                                        new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 4)))),
                            
                            new ShapeWrapper("non-45 angle (cross)",
                                             new Shape45(new Pt2D(2, 0),
                                                         new Pt2D(3, 0),
                                                         new Pt2D(3, 3),
                                                         new Pt2D(6, 3),
                                                         new Pt2D(4, 4),
                                                         new Pt2D(3, 4),
                                                         new Pt2D(3, 6),
                                                         new Pt2D(2, 6),
                                                         new Pt2D(2, 4),
                                                         new Pt2D(0, 4),
                                                         new Pt2D(0, 3),
                                                         new Pt2D(2, 3))),

                            new ShapeWrapper("non-45 angles 3",
                                             new ShapeGroup(new Shape45(new Pt2D(1, 1),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(3, 4),
                                                                        new Pt2D(7, 1),
                                                                        new Pt2D(7, 4),
                                                                        new Pt2D(8, 6),
                                                                        new Pt2D(3, 7),
                                                                        new Pt2D(6, 9),
                                                                        new Pt2D(2, 10),
                                                                        new Pt2D(0, 5)))),
                            
                            new ShapeWrapper("top-level shapes intersect",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 0),
                                                                        new Pt2D(3, 0),
                                                                        new Pt2D(0, 3)),
                                                            new Shape45(new Pt2D(3, 1),
                                                                        new Pt2D(3, 6),
                                                                        new Pt2D(1, 6),
                                                                        new Pt2D(1, 1)))),

                            new ShapeWrapper("sub-shape intersects outline",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(2, 1),
                                                                     new Pt2D(0, 3),
                                                                     new Pt2D(0, 6),
                                                                     new Pt2D(3, 3),
                                                                     new Pt2D(3, 1)),
                                                         new Shape45(new Shape45[] {
                                                                 new Shape45(new Pt2D(6, 2),
                                                                             new Pt2D(6, 4),
                                                                             new Pt2D(5, 4),
                                                                             new Pt2D(5, 2)),
                                                                 new Shape45(new Pt2D(9, 2),
                                                                             new Pt2D(7, 4),
                                                                             new Pt2D(7, 2)),
                                                             },
                                                             new Pt2D(4, 1),
                                                             new Pt2D(4, 5),
                                                             new Pt2D(7, 5),
                                                             new Pt2D(11, 1)),
                                                         new Shape45(new Pt2D(3, 4),
                                                                     new Pt2D(2, 5),
                                                                     new Pt2D(3, 5)),
                                                     },
                                                     new Pt2D(1, 0),
                                                     new Pt2D(13, 0),
                                                     new Pt2D(7, 6),
                                                     new Pt2D(1, 6)))),

                            new ShapeWrapper("sub-shapes intersect",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(1, 2),
                                                                     new Pt2D(1, 4),
                                                                     new Pt2D(4, 4),
                                                                     new Pt2D(4, 2)),
                                                         new Shape45(new Pt2D(3, 1),
                                                                     new Pt2D(3, 5),
                                                                     new Pt2D(5, 5),
                                                                     new Pt2D(5, 1)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(6, 0),
                                                     new Pt2D(6, 6),
                                                     new Pt2D(0, 6)))),

                            new ShapeWrapper("self-intersecting outline",
                                             new ShapeGroup(new Shape45(new Pt2D(4, 0),
                                                                        new Pt2D(0, 4),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 7),
                                                                        new Pt2D(1, 7),
                                                                        new Pt2D(1, 0)))),

                            new ShapeWrapper("self-intersecting sub-shape",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(2, 1),
                                                                     new Pt2D(2, 6),
                                                                     new Pt2D(7, 6),
                                                                     new Pt2D(7, 5),
                                                                     new Pt2D(1, 5),
                                                                     new Pt2D(5, 1)),
                                                         new Shape45(new Pt2D(6, 1),
                                                                     new Pt2D(9, 4),
                                                                     new Pt2D(10, 4),
                                                                     new Pt2D(10, 1)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(11, 0),
                                                     new Pt2D(11, 4),
                                                     new Pt2D(8, 7),
                                                     new Pt2D(0, 7)))),

                            new ShapeWrapper("vertex intersects edge in outline",
                                             new ShapeGroup(new Shape45(new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(4, 4),
                                                                        new Pt2D(4, 2),
                                                                        new Pt2D(3, 2),
                                                                        new Pt2D(3, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 4),
                                                                        new Pt2D(0, 1)))),                            
                            new ShapeWrapper("duplicate vertices in outline",
                                             new ShapeGroup(new Shape45(new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(6, 10),
                                                                        new Pt2D(0, 10),
                                                                        new Pt2D(0, 8),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 4),
                                                                        new Pt2D(0, 1)))),

                            new ShapeWrapper("sub-shape outside outline",
                                             new ShapeGroup(new Shape45(new Shape45(new Pt2D(6, 3),
                                                                                    new Pt2D(9, 3),
                                                                                    new Pt2D(6, 0)),
                                                                        new Pt2D(0, 1),
                                                                        new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 4)))),
                            
                            new ShapeWrapper("top-level outlines illegally nested",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 1),
                                                                        new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 8),
                                                                        new Pt2D(2, 8),
                                                                        new Pt2D(0, 6)),
                                                            new Shape45(new Pt2D(5, 5),
                                                                        new Pt2D(5, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(1, 5)))),

                            new ShapeWrapper("intersection without edge-intersection",
                                             new ShapeGroup(new Shape45(new Pt2D(0, 1),
                                                                        new Pt2D(1, 0),
                                                                        new Pt2D(2, 0),
                                                                        new Pt2D(6, 4),
                                                                        new Pt2D(6, 6),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(0, 4)),
                                                            new Shape45(new Pt2D(8, 6),
                                                                        new Pt2D(8, 8),
                                                                        new Pt2D(6, 10),
                                                                        new Pt2D(3, 10),
                                                                        new Pt2D(2, 9),
                                                                        new Pt2D(2, 6),
                                                                        new Pt2D(4, 4),
                                                                        new Pt2D(6, 4)))),
                            
                            new ShapeWrapper("sub-shape intersection without edge intersection",
                                             new ShapeGroup(new Shape45(new Shape45[] {
                                                         new Shape45(new Pt2D(1, 5),
                                                                     new Pt2D(3, 7),
                                                                     new Pt2D(7, 7),
                                                                     new Pt2D(7, 5),
                                                                     new Pt2D(3, 1),
                                                                     new Pt2D(2, 1),
                                                                     new Pt2D(1, 2)),
                                                         new Shape45(new Pt2D(7, 5),
                                                                     new Pt2D(5, 5),
                                                                     new Pt2D(3, 7),
                                                                     new Pt2D(3, 10),
                                                                     new Pt2D(4, 11),
                                                                     new Pt2D(7, 11),
                                                                     new Pt2D(9, 9),
                                                                     new Pt2D(9, 7)),
                                                         new Shape45(new Pt2D(2, 7),
                                                                     new Pt2D(1, 8),
                                                                     new Pt2D(1, 11),
                                                                     new Pt2D(2, 10)),
                                                     },
                                                     new Pt2D(0, 0),
                                                     new Pt2D(10, 0),
                                                     new Pt2D(10, 12),
                                                     new Pt2D(0, 12))))
                            
                            );
    }
    
}
